repositories {
    //TODO Organize this and do includeGroup for all...
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }
    maven { url = "https://mvn.devos.one/releases" }
    maven { url = "https://mvn.devos.one/snapshots" }
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" }
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://jitpack.io" }
    maven { url = "https://maven.ftb.dev/releases" } // FTB Mods
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }
    maven { url "https://maven.architectury.dev/" }

    maven {
        url = "https://jm.gserv.me/repository/maven-public" // JourneyMap
        content {
            includeGroup "info.journeymap"
            includeGroup "mysticdrew"
        }
    }

    maven {
        url = "https://jitpack.io/"
        content { includeGroupAndSubgroups("com.github") }
    }

    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.ryanhcode.dev/releases"
                name = "RyanHCode Maven"
            }
        }
        filter {
            includeGroup("dev.ryanhcode.sable")
            includeGroup("dev.ryanhcode.sable-companion")
            includeGroup("dev.simulated_team.simulated")
            includeGroup("dev.ryanhcode.offroad")
            includeGroup("dev.eriksonn.aeronautics")

        }
    }

    maven {
        url = "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
                metadataSources {
                    artifact()
                }
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven { url = "https://maven.shedaniel.me" } // Cloth Config, REI
    maven { url = "https://maven.blamejared.com" } // JEI
    maven { url = "https://maven.terraformersmc.com/releases" } // Mod Menu, EMI
}