# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.2.0
mod_id = buildstonetoolkit
mod_description = A mod to bring new tools that enhance the aesthetic capabilities of vanilla redstone
mod_name = Buildstone Toolkit
mod_author = HoshinOFW
mod_license = Apache License 2.0

# Maven
maven_group = com.github.hoshinofw.buildstonetoolkit
archives_name = buildstonetoolkit

# Publishing
# IDs
curseforge_id=1383196
modrinth_id=m5tBeIGD

# Curseforge data
mod_client=true
mod_server=true
curseforge_dependencies= architectury-api
modrinth_dependencies= architectury-api

# release channel: release / beta / alpha
release_channel=release