# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.4
mod_id = buildstonetoolkit
enabled_platforms = fabric,forge
mod_description = A mod to bring new tools that enhance the aesthetic capabilities of vanilla redstone
mod_name = Buildstone Toolkit
mod_author = HoshinOFW
mod_license = Apache License 2.0

#Maven
maven_group = com.github.hoshinofw.buildstonetoolkit
archives_name = buildstonetoolkit

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
mixin_extras_version = 0.3.5
architectury_api_version = 9.2.14
fabric_loader_version = 0.18.0
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.10

