pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
        maven {
            url = uri("https://maven.hoshinofw.net/releases")
        }
    }
}

plugins {
    id "com.github.hoshinofw.multiversion.multiversion-settings" version "0.6.1"
}

rootProject.name = 'buildstonetoolkit'

multiversionModules {
    common = ['common']
    fabric = ['fabric']
    forge = ['forge']
    neoforge = ['neoforge']

    patchModules = ['forge',
                    'fabric',
                    'neoforge', 'common']
}