{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hoshinofw.multiversion",
    "module": "idea-plugin",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "idea-plugin-0.0.5-base.jar",
          "url": "idea-plugin-0.0.5-base.jar",
          "size": 17708,
          "sha512": "900affec1d6353757fc163eaa245cd5ce88c2da467f4a6b366a2c72fb3f6d8168bd0d1fd543b7b2c5c67fe1290aa01652c648c25ce6aa6baf32de4b8c111a021",
          "sha256": "c6692d11e0c1ad577661ef983309bbdbd356d04da5f8d5214ae7cdea7066259e",
          "sha1": "e29ef3b3323c26ff16cede1180e78a43624885fd",
          "md5": "cdf3efd51421072890197101b3b94489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "idea-plugin-0.0.5-base.jar",
          "url": "idea-plugin-0.0.5-base.jar",
          "size": 17708,
          "sha512": "900affec1d6353757fc163eaa245cd5ce88c2da467f4a6b366a2c72fb3f6d8168bd0d1fd543b7b2c5c67fe1290aa01652c648c25ce6aa6baf32de4b8c111a021",
          "sha256": "c6692d11e0c1ad577661ef983309bbdbd356d04da5f8d5214ae7cdea7066259e",
          "sha1": "e29ef3b3323c26ff16cede1180e78a43624885fd",
          "md5": "cdf3efd51421072890197101b3b94489"
        },
        {
          "name": "idea-plugin-0.0.5.jar",
          "url": "idea-plugin-0.0.5.jar",
          "size": 261,
          "sha512": "a845f83b406e75b76a9aeb761771ea0cb0a6dbeb33477faf1e1c5427f35219a00b8f17333ebea3e980a3e0fe93c7039e212fd13efef4479226f659e555471525",
          "sha256": "725c8e58b923d8a0c1a12ac4eb9c3939b32a69a3b8961fdc76a849683a994db2",
          "sha1": "99d8076e56c8246132f5d2cddf44c48c5a008b2e",
          "md5": "a6c3c2678907882914a3209c5b0f342c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idea-plugin-0.0.5-javadoc.jar",
          "url": "idea-plugin-0.0.5-javadoc.jar",
          "size": 261,
          "sha512": "29b6952e6ed0ae729b2c097dcc9e9c3cb306bbf854be0af423068d7f9947440684f8c71d4305c5c8b5260f471b0195331b0a5f0c2c74ecc3f70557b12547fcb5",
          "sha256": "63f0b7294fe8e75fd29954357815d5fffb6486070808de51a157b6ed21bed77f",
          "sha1": "9fef27ff2be7d2509bc1c4680a86db2d5799d9cd",
          "md5": "d5826fbd55aae47fbd32f5223b283f84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idea-plugin-0.0.5-sources.jar",
          "url": "idea-plugin-0.0.5-sources.jar",
          "size": 4953,
          "sha512": "62111afa59d112035c3efd1f613886d404260f37210cec0c26b97cac2e4b9ef1bd929a420e142b76064b70de9d6b6491807f1419034e13b4ac10d16907229b2a",
          "sha256": "b288086faf5a0a0483ec7eab4658866e6ac350a898b36870d032b0152455224f",
          "sha1": "a914a9fb8c1b6e34080bd65da1aa525f4c817147",
          "md5": "e18c2b8efee911e54468ee0bfcbc0b64"
        }
      ]
    }
  ]
}
