modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Apache License 2.0"

[[mods]]
modId = "buildstonetoolkit"
version = "${version}"
displayName = "Buildstone Toolkit"
authors = "HoshinOFW"
description = '''
A mod to bring new tools that enhance the aesthetic capabilities of vanilla redstone
'''
logoFile = "icon.png"

[[dependencies.buildstonetoolkit]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.buildstonetoolkit]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.buildstonetoolkit]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "buildstonetoolkit.mixins.json"
