# Loom
enabled_platforms = fabric,neoforge

# Java
java_version=21

# Minecraft properties
minecraft_version = 1.21.1

# Loom
yarn_mappings=1.21.1+build.3

# Fabric
fabric_api_version = 0.116.11+1.21.1

# NeoForge
neoforge_version = 21.1.219
neo_form_version = 1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Mods
architectury_api_version = 13.0.8
jei_version = 19.21.0.247
ponder_version = 1.0.69
create_version = 6.0.9-170
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+62
sable_version = 1.2.2
create_simulated_version = 1.2.1
create_aeronautics_version = 1.2.1
create_offroad_version = 1.2.1
spark_version = 1.10.109